# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: formulahendry
subtitle: A Software Engineer @ Hongkou
description:
author: formulahendry
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://formulahendry.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: spfk

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/formulahendry/formulahendry.github.io.git

theme_config:
  # Header | 主菜单
  ## About Page: `hexo new page about`
  ## Tags Cloud Page: `hexo new page tags`
  menu:
    首页: /
    作品: /works
    关于: /about
  
  # Link to your avatar | 填写头像地址
  avatar: assets/img/logo.jpg

  # Small icon of Your site | 站点小图标地址
  favicon: assets/img/logo.jpg

  # Social info. Bar | 社交信息展示
  ## Keep "mailto:" in Email | 设置 Email 时保留 "mailto:"
  ## Encrypt email 加密邮件地址 http://ctrlq.org/encode/
  ## RSS requires a plugin to take effect | 使用 RSS 需先安装对应插件
  ## https://github.com/hexojs/hexo-generator-feed
  subnav:
    mail: "mailto:formulahendry@gmail.com"
    github: "https://github.com/formulahendry"
    zhihu: "https://www.zhihu.com/people/han-jun-96-36"
    weibo: "http://weibo.com/formulahendry"
    google: "https://plus.google.com/u/0/108325760150652720243"
    twitter: "https://twitter.com/formulahendry"
    linkedin: "https://cn.linkedin.com/in/jun-han"
    rss: /atom.xml
    # facebook: "#"
    # pinterest: "#"
    # QQ: "#"
    # wechat: "#"
    # douban: "#"
    # pinboard: "#"
    # stackoverflow: "#"
    # Instagram: "#"
    # segmentfault: "#"

  # Blogroll, Link exchange | 友情链接
  # friends: false
  friends:
    formulahendry MSDN Blog: https://blogs.msdn.microsoft.com/formulahendry/

  #是否开启“关于我”。
  aboutme: 码农@虹口
  #aboutme: false

  # 不蒜子网站计数设置
  # http://ibruce.info/2015/04/04/busuanzi/
  visit_counter:
    on: true
    site_visit: 到访数
    page_visit: 本页阅读量

  duoshuo: 
    on: true
    domain: formulahendry
    # 是否开启多说评论，http://duoshuo.com/create-site/
    # 使用上面网址登陆你的多说，然后创建站点，在 domain 中填入你设定的域名前半部分
    # http://<要填的部分>.duoshuo.com (domain只填上<>里的内容，不要填整个网址)

  # Background | 背景
  ## "background_sum": show images form /source/background/的图片数目
  ## "on: true": 自动随机显示这5张图片
  ## "on: false": 自定义显示图片设置background_image: 5
  background:
    on: false
    background_sum: 24
    background_image: 10

  # 百度、谷歌站长验证。填写 HTML 标签 content
  # Site Verification for Google and Baidu. HTML label content.
  google_site: zlAjmLCs5fLorMqjFd1TgfKzswUyKamRr9JML6FOnEI
  baidu_site: SVuHidI5QX

  # Fill in Google Analytics tracking ID, #e.g. UA-XXXXX-X, or Baidu Analytics hash key
  google_analytics: UA-88313303-1
  baidu_analytics: 

  # 自定义"阅读全文"链接按钮的显示文字
  # Customize the text on excerpt link
  excerpt_link: 阅读全文 #修改more>>的文字

  # A标签提示
  TipTitle: true